### ISSUE TITLE
fix: models/ModelProvider.dart not found

### ISSUE THREAD

**Issue by felangel** [salihgueler/amplify_starter#1]
Thanks for creating this awesome brick!

I noticed when generating a new project that the `main.dart` file contains an import for `models/ModelProvider.dart` which doesn't appear to be part of the brick. Let me know if I missed something and thanks again! 🙏

<img width="1537" alt="Screen Shot 2022-07-06 at 9 54 06 AM" src="https://user-images.githubusercontent.com/8855632/177580034-fef97739-7af6-4ef0-a502-8ae508309266.png">

**Comment by salihgueler** [comment]
Hi Felix, thank YOU for creating mason_cli and bricks!

I mentioned this in the documentation that, this project creates the base project for you but users need to initialize Amplify for their project. It is described in the README.md in the project that is created. 

Is it clearer now?

**Comment by felangel** [comment]
> Hi Felix, thank YOU for creating mason_cli and bricks!
> 
> I mentioned this in the documentation that, this project creates the base project for you but users need to initialize Amplify for their project. It is described in the README.md in the project that is created.
> 
> Is it clearer now?

Ah got it! So running `amplify codegen models` will generate `models/ModelProvider.dart`? Thanks for clarifying 👍

**Comment by felangel** [comment]
@salihgueler it might be interesting to create a `post_gen.dart` hook to try to automate some of the steps in the `README`. Happy to help if you think it's a good idea.

**Comment by salihgueler** [comment]
Of course! I would be really happy to discuss it!
